export const FilterOptionsList = [
    {
        id: 1,
        label: 'Verificado',
        value: 'verificado',
        isChecked: false,
    },
    {
        id: 2,
        label: 'No verificado',
        value: 'verificado',
        isChecked: false,
    },
    {
        id: 3,
        label: 'Hasta 5 proyectos',
        value: 'experiencia',
        min: 0,
        max: 5,
        isChecked: false,
    },
    {
        id: 4,
        label: '5-20 proyectos',
        value: 'experiencia',
        min: 5,
        max: 20,
        isChecked: false,
    },
    {
        id: 5,
        label: '+20 proyectos',
        value: 'experiencia',
        min: 20,
        max: 0,
        isChecked: false,
    },
    {
        id: 6,
        label: '$500-$1000/m2',
        value: 'precio',
        min: 500,
        max: 1000,
        isChecked: false,
    },
    {
        id: 7,
        label: '$1000-$5000/m2',
        value: 'precio',
        min: 1000,
        max: 5000,
        isChecked: false,
    },
    {
        id: 8,
        label: '$5000-$10000/m2',
        value: 'precio',
        min: 5000,
        max: 10000,
        isChecked: false,
    },
    {
        id: 9,
        label: '$10000-$15000/m2',
        value: 'precio',
        min: 10000,
        max: 15000,
        isChecked: false,
    },
];