export const SignUpInputsList = [
    {
        id: 1,
        name: 'name',
        placeholder: 'Nombre',
        type: 'text',
        autoComplete: 'off',
    },
    {
        id: 2,
        name: 'surName',
        placeholder: 'Apellido',
        type: 'text',
        autoComplete: 'off',
    },
    {
        id: 3,
        name: 'email',
        placeholder: 'E-mail',
        type: 'text',
        autoComplete: 'off',
    },
    {
        id: 4,
        name: 'password',
        placeholder: 'Contraseña',
        type: 'password',
        autoComplete: 'off',
    },
    {
        id: 5,
        name: 'precio',
        placeholder: 'Precio por m2 en ARS',
        type: 'number',
        autoComplete: 'off',
    },
    {
        id: 6,
        name: 'localidad',
        placeholder: 'Localidad',
        type: 'text',
        autoComplete: 'off',
    },
    {
        id: 7,
        name: 'phoneNumber',
        placeholder: 'Numero de contacto',
        type: 'tel',
        autoComplete: 'off',
    },
]